# Define job order
stages:
  - lib-build
  
# Define library files
.lib-build-files: &lib-build-files
  only:
    refs:
      - stable

# Create library for macos
lib-build-macos:
  <<: *lib-build-files
  stage: lib-build
  tags:
    - osx
  script:
    - git clean -xfd
    - ./autogen.sh
    - ./configure
    - make
    - mkdir release
    - make prefix=$PWD/release install
    - make prefix=$HOME/builds/release/ingescape/usr/local/ install
    - cd deploy
    - tar zcvf ../libsodium.tgz *
    - cd ..
  artifacts:
    paths:
      - libsodium.tgz
    name: "lib-macos-release-x64"
    expire_in: 1 day
  dependencies: []
