# Define job order
stages:
  - build-lib
  - installer-lib
  - deploy-lib
  
# Define library files
.build-lib-files: &build-lib-files
  only:
    changes:
      - ./**
    refs:
      - stable

# Create library for macos
lib-macos-release-x64:
  <<: *build-lib-files
  stage: build-lib
  tags:
    - osx
  script:
    - git clean -xfd
    - ./autogen.sh
    - ./configure
    - make
    - mkdir build
    - make prefix=$PWD/build install
    - make prefix=$HOME/builds/release/x64/usr/local/ install
    - cd build
    - tar zcvf ../libsodium.tgz *
    - cd ..
  artifacts:
    paths:
      - libsodium.tgz
    name: "lib-macos-release-x64"
    expire_in: 1 day
  dependencies: []
